language: node_js
sudo: false
node_js:
  - "stable"
  - "8"
  - "6"

before_script:
  - 'if [ "$TRAVIS_NODE_VERSION" = "6" ]; then npm run prepare; fi'

before_deploy:
  - cd example && npm install && cd ..
  - mkdir _deploy
  - cp example/bundle.js example/index.html example/frame-bundle.js example/frame.html _deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: _deploy
  on:
    branch: master
    node: stable
